# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'myacrpull'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $SOURCE_REG="Amardip"
      $TARGET_REG="testamardip"
      $repo="amardipnode"
      $tag="v3"
      $passwordOfSrcACR="fCb8Nx+i8SckkMD7DY6acfuIqoQ/=D8c"
      # Get list of source repositories
            $REPO_LIST=$(az acr repository list --name testamardip --username testamardip --password Vgf2mazdXi54tUOqmj0UCeJ8F=zkxt4k --output tsv)
            
            
            # Enumerate tags and import to target registry
            foreach ($repo in $REPO_LIST)
            {
            $TAGS_LIST=$(az acr repository show-tags --name testamardip --username testamardip --password Vgf2mazdXi54tUOqmj0UCeJ8F=zkxt4k --repository $repo  --output tsv)
            foreach ($tag in $TAGS_LIST){
            echo "This image is alreday exist in "
      	  Exit 0 
                  }
            }
      	  
      	  az acr import --name testamardip --source amardip.azurecr.io/$repo":"$tag --username Amardip --password fCb8Nx+i8SckkMD7DY6acfuIqoQ/=D8c
          echo "your image is now alvialiable "