# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'myacrpull'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $SOURCE_REG="Amardip"
      $TARGET_REG="testamardip"
      $repo="amardipu", "amardipy" 
      $tag="latest"
      $passwordOfSrcACR="fCb8Nx+i8SckkMD7DY6acfuIqoQ/=D8c"
      
       # Get list of source repositories
       $REPO_LIST=$(az acr repository list --name testamardip --username testamardip --password /5mP9ne9JYg2ZXFZEoCZnkGwUV16n68Z --output tsv)
            
            foreach ($r in $repo) {
            # Enumerate tags and import to target registry
            foreach ($r in $REPO_LIST)
            {
                  $TAGS_LIST=$(az acr repository show-tags --name testamardip --username testamardip --password /5mP9ne9JYg2ZXFZEoCZnkGwUV16n68Z --repository $r  --output tsv)
                      foreach ($tag in $TAGS_LIST){
                          echo "$r":"$tag This image is alvialiable "
      	                 
                  }
            }
      
            
      	  
      	  az acr import --name testamardip --source amardip.azurecr.io/$r":"$tag --username amardip --password uTB/5JBpZ58HNrLGjJvWqrgq4+4e1u3b
      	  echo "your image is now alvialiable "
      
      }