# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'myacrpull'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $SOURCE_REG=Amardip
      $TARGET_REG=testamardip
      $repo=amardipython
      $tag=v2
      $passwordOfSrcACR=fCb8Nx+i8SckkMD7DY6acfuIqoQ/=D8c
      
      
      # Get list of source repositories
      $REPO_LIST=$(az acr repository list --name $SOURCE_REG --username $SOURCE_REG --password $passwordOfSrcACR --output tsv)
      
      
      # Enumerate tags and import to target registry
      foreach ($repo in $REPO_LIST)
      {
      $TAGS_LIST=$(az acr repository show-tags --name $SOURCE_REG --username $SOURCE_REG --password $passwordOfSrcACR --repository $repo  --output tsv)
      foreach ($tag in $TAGS_LIST){
      echo "Importing $repo":"$tag"
      az acr import --name $TARGET_REG --source $SOURCE_REG.azurecr.io/$repo":"$tag --username $SOURCE_REG --password $passwordOfSrcACR
      }
      }
